import React from 'react'
import { Link } from 'react-router-dom'
import { Lightbulb, Rocket, Users } from 'lucide-react'

const Home: React.FC = () => {
  return (
    <div className="text-center">
      <h1 className="text-4xl font-bold mb-6">Welcome to NameGenius</h1>
      <p className="text-xl mb-8">Discover the perfect name for your project with AI-powered suggestions</p>
      
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12">
        <FeatureCard
          icon={<Lightbulb className="w-12 h-12 text-yellow-500" />}
          title="AI-Powered Suggestions"
          description="Get creative and unique name ideas generated by advanced AI models"
        />
        <FeatureCard
          icon={<Rocket className="w-12 h-12 text-blue-500" />}
          title="Instant Analysis"
          description="Receive detailed reports on name suitability and domain availability"
        />
        <FeatureCard
          icon={<Users className="w-12 h-12 text-green-500" />}
          title="Collaborative Projects"
          description="Work together with your team to find the perfect name"
        />
      </div>
      
      <Link
        to="/generate"
        className="bg-indigo-600 text-white px-6 py-3 rounded-lg text-lg font-semibold hover:bg-indigo-700 transition duration-300"
      >
        Start Generating Names
      </Link>
    </div>
  )
}

const FeatureCard: React.FC<{ icon: React.ReactNode; title: string; description: string }> = ({ icon, title, description }) => {
  return (
    <div className="bg-white p-6 rounded-lg shadow-md">
      <div className="flex justify-center mb-4">{icon}</div>
      <h3 className="text-xl font-semibold mb-2">{title}</h3>
      <p className="text-gray-600">{description}</p>
    </div>
  )
}

export default Home